-- SQL
CREATE TABLE items (
-- column name
--    data type
--             extras??
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	item_name TEXT NOT NULL,
	description TEXT,
	completed BOOLEAN DEFAULT false,
	created TIMESTAMPTZ DEFAULT now()
);

INSERT INTO items (item_name, description)
    VALUES ('avocado', 'delicious and green');
   
INSERT INTO items (item_name) VALUES ('box fan');

INSERT INTO items(description) VALUES ('this is a description');